target 'MyApp' do
# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
# use_frameworks!

# Pods for MyApp
pod 'OneSignal'

#target 'MyAppTests' do
#  inherit! :search_paths
# Pods for testing
#end

end
